export class ConfTecnica
{
    idEncRepetitivo:number; 
    idCondicion:number;
    idConfTecnica:number;
    nombreCondicion:string;
    referenciaCondicion:string;
    storeProcedure:string;
    opcion:number;
    comentario:string;
    usuarioInsert:string;
    usuarioModifica:string;
    usuarioBaja:string;
    fechaInsert:Date;
    fechaModifica:Date;
    fechaBaja:Date;
    estatus:boolean;
    estatusTransaccion:boolean;
}